---
- name: Move old container to new | Remove any existing {{ service }}_new container
  docker_container:
    name: "{{ service }}_new"
    privileged: "{{ privileged | default('false') }}"
    network_mode: "{{ network_mode | default(omit) }}"
    pid_mode: "{{ pid_mode | default(omit) }}"
    ipc_mode: "{{ ipc_mode | default(omit) }}"
    state: absent

- name: Move old container to new | Check if {{ service }}_old exists
  shell: /bin/docker ps -a | grep "{{ service }}_old"
  register: old_check
  ignore_errors: true

- name: Move old container to new | Confirming ability to rollback {{ service }}
  fail: msg='No {{service}}_old  container found, cannot rollback'
  when: "old_check.rc == 1"

- name: Move old container to new | Move {{ service }}_old container to {{ service }}_new
  command: /bin/docker rename "{{ service }}_old" "{{ service }}_new"
  when: "old_check.rc == 0"
