---
- name: Restart active container | Check if {{ service }}_active exists
  shell: /bin/docker ps -a | grep "{{ service }}_active"
  register: active_check
  ignore_errors: true

- name: Restart active container | Confirm ability to restart "{{ service }}"
  fail: msg='Unable to find "{{ service }}_active" to restart'
  when: "active_check.rc == 1"

- name: Restart active container | Restarting "{{ service }}"
  shell: /bin/docker restart "{{ service }}_active"
  when: "active_check.rc == 0"
