---
- name: Rollback new CUSTOM container | Gather container log from {{ service }}_new
  shell: docker logs "{{ service }}_new"
  register: container_logs

- name: Rollback new CUSTOM container | Stopping {{ service }}_new, due to {{ service }}_new not starting
  docker_container:
    name: "{{ service }}_new"
    state: absent
    force_kill: true
    privileged: "{{ privileged | default('false') }}"
    network_mode: "{{ network_mode | default(omit) }}"
    pid_mode: "{{ pid_mode | default(omit) }}"
    ipc_mode: "{{ ipc_mode | default(omit) }}"

- name: Rollback new CUSTOM container | Starting original {{ service }}_active
  docker_container:
    name: "{{ service }}_active"
    state: started
    privileged: "{{ privileged | default('false') }}"
    network_mode: "{{ network_mode | default(omit) }}"
    pid_mode: "{{ pid_mode | default(omit) }}"
    ipc_mode: "{{ ipc_mode | default(omit) }}"
  when: active_check.rc == 0


- name: Rollback new CUSTOM container | Output {{ service }}_new logs
  debug: var=container_logs

- name: Rollback new CUSTOM container | {{ service }}_new container did not start
  fail:
    msg: "{{ service }}_new did not pass basic tests, aborting this deployment run"
  when: no_fail_msg is not defined
