---
- name: Start New API Container | Start {{ service }}_new API container
  docker_container:
    name: "{{ service }}_new"
    state: started
    privileged: "{{ privileged | default('false') }}"
    network_mode: "{{ network_mode | default(omit) }}"
    pid_mode: "{{ pid_mode | default(omit) }}"
    ipc_mode: "{{ ipc_mode | default(omit) }}"
