---
type: api
image: centos-source-cinder-api
base_service: cinder
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/cinder-api:/var/lib/kolla/config_files
  - /var/log/cinder:/var/log/cinder
  - /etc/pki/tls/:/var/lib/kolla/config_files-tls:ro
ports:
  - 8776
static_ip: 192.168.185.41
notify: false
run_command: "cinder-api"
config_files:
  - /var/lib/kolla/config_files/cinder.conf:/etc/cinder/cinder.conf
  - /var/lib/kolla/config_files-tls/certs/cloud.crt:/etc/pki/tls/certs/cloud.crt
  - /var/lib/kolla/config_files-tls/private/cloud.key:/etc/pki/tls/private/cloud.key
permissions:
  - /var/log/cinder
