---
type: rpc
image: centos-source-cinder-backup
base_service: cinder
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/cinder-backup:/var/lib/kolla/config_files:ro
  - /var/log/cinder:/var/log/cinder
  - /tmp/cinder-backup:/tmp/cinder-backup
notify: true
run_command: "cinder-backup"
config_files:
  - /var/lib/kolla/config_files/cinder.conf:/etc/cinder/cinder.conf
permissions:
  - /var/log/cinder
