---
type: rpc
image: centos-source-heat-engine
base_service: heat
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/heat-engine:/var/lib/kolla/config_files
  - /var/log/heat:/var/log/heat
notify: False
run_command: "heat-engine"
config_files:
  - /var/lib/kolla/config_files/heat.conf:/etc/heat/heat.conf
permissions:
  - /var/log/heat
