---
type: api
image: centos-source-neutron-server
base_service: neutron
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/neutron-server:/var/lib/kolla/config_files:ro
  - /var/log/neutron:/var/log/neutron
  - /etc/pki/tls/:/var/lib/kolla/config_files-tls:ro
ports:
 - 9696
static_ip: 192.168.185.21
notify: false
run_command: "neutron-server --config-file=/etc/neutron/plugins/ml2/ml2_conf.ini --config-file=/etc/neutron/neutron.conf"
config_files:
  - /var/lib/kolla/config_files/neutron.conf:/etc/neutron/neutron.conf
  - /var/lib/kolla/config_files/api-paste.ini:/etc/neutron/api-paste.ini
  - /var/lib/kolla/config_files/policy.d/0001.policy.json:/etc/neutron/policy.d/0001.policy.json
  - /var/lib/kolla/config_files/policy.d/0002.policy.json:/etc/neutron/policy.d/0002.policy.json
  - /var/lib/kolla/config_files/plugins/ml2/ml2_conf.ini:/etc/neutron/plugins/ml2/ml2_conf.ini
  - /var/lib/kolla/config_files-tls/certs/cloud.crt:/etc/pki/tls/certs/cloud.crt
  - /var/lib/kolla/config_files-tls/private/cloud.key:/etc/pki/tls/private/cloud.key
permissions:
  - /var/log/neutron
