---
type: rpc
image: centos-source-neutron-openvswitch-agent
base_service: neutron
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/neutron-openvswitch-agent:/var/lib/kolla/config_files:ro
  - /var/log/neutron:/var/log/neutron
  - /run/openvswitch:/run/openvswitch:shared
  - /tmp/neutron-openvswitch-agent:/tmp/neutron-openvswitch-agent
notify: False
privileged: True
network_mode: host
no_rabbit_is_fatal: True
run_command: "neutron-openvswitch-agent --config-file=/etc/neutron/plugins/ml2/ml2_conf.ini --config-file=/etc/neutron/neutron.conf"
config_files:
  - /var/lib/kolla/config_files/neutron.conf:/etc/neutron/neutron.conf
  - /var/lib/kolla/config_files/plugins/ml2/ml2_conf.ini:/etc/neutron/plugins/ml2/ml2_conf.ini
  - /var/lib/kolla/config_files/rootwrap.conf:/etc/neutron/rootwrap.conf
permissions:
  - /var/log/neutron
