---
type: api
image: centos-source-nova-api
base_service: nova
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/nova-api-metadata:/var/lib/kolla/config_files:ro
  - /var/log/nova:/var/log/nova
ports:
 - 8775
privileged: true
static_ip: 192.168.185.33
notify: false
run_command: "nova-api-metadata --config-file=/etc/nova/nova.conf"
config_files:
  - /var/lib/kolla/config_files/nova.conf:/etc/nova/nova.conf
permissions:
  - /var/log/nova
  - /var/lib/nova
