---
type: api
image: centos-source-nova-api
base_service: nova
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/nova-api:/var/lib/kolla/config_files:ro
  - /var/log/nova:/var/log/nova
  - /etc/els:/var/lib/kolla/config_files_els:ro
ports:
 - 8774
static_ip: 192.168.185.31
notify: false
run_command: "nova-api --config-file=/etc/nova/nova.conf"
config_files:
  - /var/lib/kolla/config_files/nova.conf:/etc/nova/nova.conf
  - /var/lib/kolla/config_files/policy.d/0001.policy.json:/etc/nova/policy.d/0001.policy.json
  - /var/lib/kolla/config_files/policy.d/0002.policy.json:/etc/nova/policy.d/0002.policy.json

permissions:
  - /var/log/nova
  - /var/lib/nova
