---
type: rpc
image: centos-source-nova-compute
base_service: nova
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/hosts:/etc/hosts
  - /etc/kolla/nova-compute:/var/lib/kolla/config_files:ro
  - /var/log/nova:/var/log/nova
  - /var/lib/nova:/var/lib/nova
  - /tmp/nova-compute:/tmp/nova-compute
  - /run/libvirt:/run/libvirt:shared
  - /run/openvswitch:/run/openvswitch:shared
  - /dev:/dev
  - /lib/modules:/lib/modules
  - /var/lib/libvirt:/var/lib/libvirt
privileged: true
notify: true
network_mode: host
run_command: "nova-compute --config-file=/etc/nova/nova.conf"
config_files:
  - /var/lib/kolla/config_files/nova.conf:/etc/nova/nova.conf
  - /var/lib/kolla/config_files/interfaces.template:/etc/nova/interfaces.template
permissions:
  - /var/log/nova
  - /var/lib/nova
