---
type: custom
image: centos-source-octavia-housekeeping
base_service: octavia
volumes:
  - /etc/localtime:/etc/localtime:ro
  - /etc/kolla/octavia-housekeeping:/var/lib/kolla/config_files
  - /var/log/octavia:/var/log/octavia
notify: false
run_command: "octavia-housekeeping"
config_files:
  - /var/lib/kolla/config_files/octavia.conf:/etc/octavia/octavia.conf
  - /var/lib/kolla/config_files/certs/private/cakey.pem:/etc/octavia/certs/private/cakey.pem
  - /var/lib/kolla/config_files/certs/ca_01.pem:/etc/octavia/certs/ca_01.pem
  - /var/lib/kolla/config_files/certs/client.pem:/etc/octavia/certs/client.pem
permissions:
  - /var/log/octavia
container_checkcmd: "netstat -alnp | grep ESTABLISHED | grep ':3306'"
